-- 기본키
ALTER TABLE "USERS"
ADD CONSTRAINT "PK_USERS" PRIMARY KEY ("user_id");

ALTER TABLE "PARTS"
ADD CONSTRAINT "PK_PARTS" PRIMARY KEY ("part_id");

ALTER TABLE "ESTIMATES"
ADD CONSTRAINT "PK_ESTIMATES" PRIMARY KEY ("estimated_id");

ALTER TABLE "ESTIMATE_ITEMS"
ADD CONSTRAINT "PK_ESTIMATE_ITEMS" PRIMARY KEY ("item_id");

ALTER TABLE "PART_SPECS"
ADD CONSTRAINT "PK_PART_SPECS" PRIMARY KEY ("spec_id");

ALTER TABLE "PRICE_HISTORY"
ADD CONSTRAINT "PK_PRICE_HISTORY" PRIMARY KEY ("price_history_id");

ALTER TABLE "RESELL_POSTS"
ADD CONSTRAINT "PK_RESELL_POSTS" PRIMARY KEY ("post_id");

ALTER TABLE "CARTS"
ADD CONSTRAINT "PK_CARTS" PRIMARY KEY ("cart_id");
    
ALTER TABLE "CART_ITEMS"
ADD CONSTRAINT "PK_CART_ITEMS" PRIMARY KEY ("cart_item_id");
    
ALTER TABLE "PERFORMANCE_TIER"
ADD CONSTRAINT "PK_PERFORMANCE_TIER" PRIMARY KEY ("tier_id");
    
-- UNIQUE
ALTER TABLE "USERS"
ADD CONSTRAINT "UQ_USERS_EMAIL" UNIQUE ("email");

ALTER TABLE "USERS"
ADD CONSTRAINT "UQ_USERS_NICKNAME" UNIQUE ("nickname");

ALTER TABLE "PARTS"
ADD CONSTRAINT "UQ_PARTS_PRODUCT_URL" UNIQUE ("product_url");

ALTER TABLE "ESTIMATE_ITEMS"
ADD CONSTRAINT "UQ_ESTIMATE_ITEM_PART" UNIQUE ("estimated_id", "part_id");

ALTER TABLE "PART_SPECS"
ADD CONSTRAINT "UQ_PART_SPECS" UNIQUE ("part_id", "spec_key", "spec_value");

ALTER TABLE "PRICE_HISTORY"
ADD CONSTRAINT "UQ_PRICE_HISTORY_DAY" UNIQUE ("part_id", "recorded_at");

ALTER TABLE "CARTS" 
ADD CONSTRAINT "UQ_CARTS_USER" UNIQUE ("user_id");
    
ALTER TABLE "CART_ITEMS"
ADD CONSTRAINT "CK_CART_ITEMS_QUANTITY" CHECK ("quantity" > 0);
    
ALTER TABLE "CART_ITEMS"
ADD CONSTRAINT "UQ_CART_ITEMS_CART_PART" UNIQUE ("cart_id", "part_id");

ALTER TABLE "PERFORMANCE_TIER"
ADD CONSTRAINT "UQ_PERFORMANCE_TIER_PART" UNIQUE ("part_id");
    
-- FOREIGN KEY
ALTER TABLE "ESTIMATES"
ADD CONSTRAINT "FK_ESTIMATE_USER"
FOREIGN KEY ("user_id") REFERENCES "USERS" ("user_id");

ALTER TABLE "ESTIMATE_ITEMS"
ADD CONSTRAINT "FK_ESTIMATE_ITEM_PART"
FOREIGN KEY ("part_id") REFERENCES "PARTS" ("part_id");

ALTER TABLE "ESTIMATE_ITEMS"
ADD CONSTRAINT "FK_ESTIMATE_ITEM_ESTIMATE"
FOREIGN KEY ("estimated_id") REFERENCES "ESTIMATES" ("estimated_id");

ALTER TABLE "PART_SPECS"
ADD CONSTRAINT "FK_PART_SPECS_PART"
FOREIGN KEY ("part_id") REFERENCES "PARTS" ("part_id");

ALTER TABLE "PRICE_HISTORY"
ADD CONSTRAINT "FK_PRICE_HISTORY_PART"
FOREIGN KEY ("part_id") REFERENCES "PARTS" ("part_id");

ALTER TABLE "RESELL_POSTS"
ADD CONSTRAINT "FK_POST_SELLER"
FOREIGN KEY ("seller_id") REFERENCES "USERS" ("user_id");

ALTER TABLE "RESELL_POSTS"
ADD CONSTRAINT "FK_POST_PART"
FOREIGN KEY ("part_id") REFERENCES "PARTS" ("part_id");

ALTER TABLE "CARTS"
    ADD CONSTRAINT "FK_CARTS_USER"
    FOREIGN KEY ("user_id")
    REFERENCES "USERS" ("user_id");
    
ALTER TABLE "CART_ITEMS"
    ADD CONSTRAINT "FK_CART_ITEMS_CART"
    FOREIGN KEY ("cart_id")
    REFERENCES "CARTS" ("cart_id");
    
ALTER TABLE "CART_ITEMS"
    ADD CONSTRAINT "FK_CART_ITEMS_PART"
    FOREIGN KEY ("part_id")
    REFERENCES "PARTS" ("part_id");
    
ALTER TABLE "PERFORMANCE_TIER"
ADD CONSTRAINT "Fk_PERFORMANCE_TIER_PARTS"
FOREIGN KEY ("part_id") REFERENCES "PARTS" ("part_id");


-- CHECK
ALTER TABLE "USERS"
ADD CONSTRAINT "CK_USERS_STATUS"
CHECK ("status" IN ('ACTIVE', 'INACTIVE', 'BLOCKED'));

ALTER TABLE "USERS"
ADD CONSTRAINT "CK_USERS_LOGIN_FAIL"
CHECK ("login_fail_count" >= 0);

ALTER TABLE "PARTS"
ADD CONSTRAINT "CK_PART_CATEGORY"
CHECK ("category" IN ('CPU', 'MAINBOARD', 'SSD', 'RAM', 'PSU', 'GPU', 'CASE', 'COOLER'));

ALTER TABLE "PARTS"
ADD CONSTRAINT "CK_PART_PRICE"
CHECK ("price" >= 0);

ALTER TABLE "PARTS"
ADD CONSTRAINT "CK_PART_DISCONTINUED"
CHECK ("is_discontinued" IN ('Y', 'N'));

ALTER TABLE "ESTIMATES"
ADD CONSTRAINT "CK_ESTIMATE_SHARED"
CHECK ("is_shared" IN ('Y', 'N'));

ALTER TABLE "ESTIMATES"
ADD CONSTRAINT "CK_ESTIMATE_RECOMMEND"
CHECK ("is_recommend" IN ('Y', 'N'));

ALTER TABLE "ESTIMATES"
ADD CONSTRAINT "CK_ESTIMATE_PRICE"
CHECK ("total_price" >= 0 AND "budget_max" >= 0 AND "total_power" >= 0);

ALTER TABLE "ESTIMATE_ITEMS"
ADD CONSTRAINT "CK_ESTIMATE_QTY_INT"
CHECK ("quantity" = TRUNC("quantity")); -- 소수점 버림

ALTER TABLE "ESTIMATES"
ADD CONSTRAINT "CK_ESTIMATE_USAGE"
CHECK (
    "usage_type" IN (
        'OFFICE',
        'GAMING',
        'DEVELOPMENT',
        'CREATOR'
    )
);

ALTER TABLE "PRICE_HISTORY"
ADD CONSTRAINT "CK_PRICE_HISTORY_PRICE"
CHECK ("dateprice" > 0);

ALTER TABLE "PRICE_HISTORY"
ADD CONSTRAINT "CK_PRICE_HISTORY_FIELD"
CHECK (REGEXP_LIKE("Field", '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'));

ALTER TABLE "RESELL_POSTS"
ADD CONSTRAINT "CK_RESELL_PRICE"
CHECK ("price" >= 0);

ALTER TABLE "PERFORMANCE_TIER"
ADD CONSTRAINT "CK_PERFORMANCE_TIER" 
CHECK ("tier" IN('보급','중급','고급','최상급'));

COMMIT;