-- 시퀀스 삭제
-- ============================================================
-- DROP SEQUENCE "SEQ_ESTIMATE_ITEMS";
-- DROP SEQUENCE "SEQ_PART_SPECS";
-- DROP SEQUENCE "SEQ_PRICE_HISTORY";
-- DROP SEQUENCE "SEQ_RESELL_POSTS";
-- DROP SEQUENCE "SEQ_ESTIMATES";
-- DROP SEQUENCE "SEQ_PARTS";
-- DROP SEQUENCE "SEQ_USERS";
-- DROP SEQUENCE "SEQ_CARTS";
-- DROP SEQUENCE "SEQ_CART_ITEMS";
-- DROP SEQUENCE "SEQ_PERFORMANCE_TIER"

CREATE SEQUENCE "SEQ_USERS" START WITH 7 INCREMENT BY 1;
CREATE SEQUENCE "SEQ_PARTS" START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE "SEQ_PART_SPECS" START WITH 2000 INCREMENT BY 1;
CREATE SEQUENCE "SEQ_ESTIMATES" START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE "SEQ_ESTIMATE_ITEMS" START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE "SEQ_PRICE_HISTORY" START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE "SEQ_RESELL_POSTS" START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE "SEQ_CARTS" START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE "SEQ_CART_ITEMS" START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE "SEQ_PERFORMANCE_TIER" START WITH 1 INCREMENT BY 1;